Repository p2hacks2022/post-team07, pull requests merged in 2022-12, with the labels that each got.

#40 [feat] GameSceneでランダムに木が生成されるようにした
  KamisamaIntern/Assets/Tanaka_Folder/Scean_Tanaka/GameScene.unity
  KamisamaIntern/Assets/Tanaka_Folder/Scripts_Tanaka/RandomTreeMake_Manager.cs
  KamisamaIntern/UserSettings/EditorUserSettings.asset
Labels: enhancement 💪, add :hugs:

#39 [feat]ゲームシーンで用いる制限時間機能を追加、経過後エンディングシーンへ遷移
  KamisamaIntern/Assets/Suebayashi_Folder/TimerCount.meta
  KamisamaIntern/Assets/Suebayashi_Folder/TimerCount/AddTimeLimit.unity
  KamisamaIntern/Assets/Suebayashi_Folder/TimerCount/AddTimeLimit.unity.meta
  KamisamaIntern/Assets/Suebayashi_Folder/TimerCount/CountDownTimer.cs
  KamisamaIntern/Assets/Suebayashi_Folder/TimerCount/CountDownTimer.cs.meta
  KamisamaIntern/UserSettings/EditorUserSettings.asset
  KamisamaIntern/UserSettings/Layouts/CurrentMaximizeLayout.dwlt
Labels: enhancement 💪, add :hugs:

#73 [feat] カード選択ターンとシミュレートターンをフラグによって切り替えるようにベース処理を作成した
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/CardController.cs
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/CardController.cs.meta
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/RenewalCardScene.unity
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/RenewalCardScene.unity.meta
  KamisamaIntern/Assets/Suebayashi_Folder/TimerCount/CountDownTimer.cs
Labels: enhancement 💪, add :hugs:

#75 [fix] 山札から手札へカードが移動する処理を修正し、再実装した
  KamisamaIntern/Assets/Image/CardImages/card_spine.png
  KamisamaIntern/Assets/Image/CardImages/card_spine.png.meta
  KamisamaIntern/Assets/Image/CardImages/heavy_rain.png
  KamisamaIntern/Assets/Image/CardImages/heavy_rain.png.meta
  KamisamaIntern/Assets/Image/CardImages/sun.png
  KamisamaIntern/Assets/Image/CardImages/sun.png.meta
  KamisamaIntern/Assets/Image/CardImages/virus.png
  KamisamaIntern/Assets/Image/CardImages/virus.png.meta
  KamisamaIntern/Assets/Image/CardImages/world_tree.png
  KamisamaIntern/Assets/Image/CardImages/world_tree.png.meta
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/AddCard.cs
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/AddCard.cs.meta
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/CardController.cs
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/DeckController.cs
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/RenewalCardScene.unity
Labels: fix :hammer:

#76 [add] 家、農場、工場の木を消費して回復する機能の追加
  KamisamaIntern/Assets/Image/world tree.png
  KamisamaIntern/Assets/Image/world tree.png.meta
  KamisamaIntern/Assets/Tanaka_Folder/Scene_Tanaka/StudyUnit_Demo.unity
  KamisamaIntern/Assets/Tanaka_Folder/Scripts_Tanaka/FarmDurabilityValueRecovery.cs
  KamisamaIntern/Assets/Tanaka_Folder/Scripts_Tanaka/FarmDurabilityValueRecovery.cs.meta
  KamisamaIntern/Assets/Tanaka_Folder/Scripts_Tanaka/FarmHealthController.cs
  KamisamaIntern/Assets/Tanaka_Folder/Scripts_Tanaka/FarmHealthController.cs.meta
  KamisamaIntern/Assets/Tanaka_Folder/Scripts_Tanaka/WorldTreeController.cs
  KamisamaIntern/Assets/Tanaka_Folder/Scripts_Tanaka/WorldTreeController.cs.meta
Labels: enhancement 💪, add :hugs:

#87 [fix] カードを選択する方式を「カード選択➡決定ボタン」に変更
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/AddCard.cs
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/Card.cs
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/CardController.cs
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/CardData.meta
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/CardData/Card.cs
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/CardData/Card.cs.meta
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/CardData/CardDataBase.cs
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/CardData/CardDataBase.cs.meta
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/CardData/CardInfomation.cs
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/CardData/CardInfomation.cs.meta
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/CardData/Data.meta
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/CardData/Data/CardDataBase.asset
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/CardData/Data/CardDataBase.asset.meta
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/CardData/Data/heavy_rain.asset
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/CardData/Data/heavy_rain.asset.meta
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/CardData/Data/industrial_revolution.asset
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/CardData/Data/industrial_revolution.asset.meta
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/CardData/Data/innseki.asset
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/CardData/Data/innseki.asset.meta
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/CardData/Data/kaminari.asset
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/CardData/Data/kaminari.asset.meta
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/CardData/Data/mutant.asset
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/CardData/Data/mutant.asset.meta
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/CardData/Data/rain.asset
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/CardData/Data/rain.asset.meta
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/CardData/Data/starting_agriculture.asset
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/CardData/Data/starting_agriculture.asset.meta
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/CardData/Data/sun.asset
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/CardData/Data/sun.asset.meta
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/CardData/Data/virus.asset
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/CardData/Data/virus.asset.meta
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/CardData/Data/world_tree.asset
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/CardData/Data/world_tree.asset.meta
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/CurSorOnCard.cs
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/Prefab/CardImage.prefab
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/RenewalCardScene.unity
  KamisamaIntern/Assets/Suebayashi_Folder/TimerCount/CountDownTimer.cs
Labels: fix :hammer:, add :hugs:

#89 [add] ゲームシーン、マップの再設置。家、農業、工場の耐久値回復
  KamisamaIntern/Assets/Scenes/GameScene_Main.unity
  KamisamaIntern/Assets/Scenes/GameScene_Main.unity.meta
  KamisamaIntern/Assets/Shinya_Folder/Resources/Animal.prefab
  KamisamaIntern/Assets/Shinya_Folder/Resources/Human 1.prefab
  KamisamaIntern/Assets/Shinya_Folder/Resources/Human 1.prefab.meta
  KamisamaIntern/Assets/Shinya_Folder/Resources/Human.prefab
  KamisamaIntern/Assets/Tanaka_Folder/Prefab_Tanaka/RandomTreePutManager.prefab
  KamisamaIntern/Assets/Tanaka_Folder/Prefab_Tanaka/RandomTreePutManager.prefab.meta
  KamisamaIntern/Assets/Tanaka_Folder/Prefab_Tanaka/sea.prefab
  KamisamaIntern/Assets/Tanaka_Folder/Prefab_Tanaka/tree.prefab
  KamisamaIntern/Assets/Tanaka_Folder/Scene_Tanaka/Demo_GameScene.unity
  KamisamaIntern/Assets/Tanaka_Folder/Scene_Tanaka/Demo_GameScene.unity.meta
  KamisamaIntern/Assets/Tanaka_Folder/Scene_Tanaka/StudyUnit_Farm.unity
  KamisamaIntern/Assets/Tanaka_Folder/Scene_Tanaka/StudyUnit_Farm.unity.meta
  KamisamaIntern/Assets/Tanaka_Folder/Scripts_Tanaka/FarmController.cs
  KamisamaIntern/Assets/Tanaka_Folder/Scripts_Tanaka/FarmDurabilityValueRecovery.cs
  KamisamaIntern/Assets/Tanaka_Folder/Unit_Tanaka/Tree.prefab
  KamisamaIntern/Assets/Tanaka_Folder/Unit_Tanaka/field.prefab
  KamisamaIntern/Assets/Tanaka_Folder/Unit_Tanaka/field.prefab.meta
  KamisamaIntern/ProjectSettings/EditorBuildSettings.asset
  KamisamaIntern/ProjectSettings/TagManager.asset
Labels: enhancement 💪, fix :hammer:, add :hugs:, reserve :handbag:

#90 [fix] 比率をウィンドウに毎度合わせるよう設定を変更
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/Prefab/CardImage.prefab
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/RenewalCardScene 1.unity
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/RenewalCardScene 1.unity.meta
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/Ver2_CardScene.unity
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/Ver2_CardScene.unity.meta
Labels: fix :hammer:

#95 [add]ゲームのタイトル・エンディングの一枚絵とBGMの取り込みとゲームシーンの統合を行いました。
  KamisamaIntern/Assets/BGM.meta
  KamisamaIntern/Assets/BGM/FailedEDBGM.mp3
  KamisamaIntern/Assets/BGM/FailedEDBGM.mp3.meta
  KamisamaIntern/Assets/BGM/OPBGM.mp3
  KamisamaIntern/Assets/BGM/OPBGM.mp3.meta
  KamisamaIntern/Assets/BGM/SuccessEDBGM.mp3
  KamisamaIntern/Assets/BGM/SuccessEDBGM.mp3.meta
  KamisamaIntern/Assets/Image/OP_Title.png.meta
  KamisamaIntern/Assets/Shinya_Folder/Scenes/StoryScene.unity
  KamisamaIntern/Assets/Shinya_Folder/Scripts/StorySceneController.cs
  KamisamaIntern/Assets/Suebayashi_Folder/EndingScene.unity
  KamisamaIntern/Assets/Suebayashi_Folder/TitleScene.unity
  KamisamaIntern/Assets/Tanaka_Folder/Scene_Tanaka/Demo_GameScene.unity
  KamisamaIntern/ProjectSettings/EditorBuildSettings.asset
Labels: try out :face_with_head_bandage:, add :hugs:, reserve :handbag:

#96 [fix] マウスカーソルをカードに置いた際にカードの効果がわかるようにした
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/CardController.cs
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/CardData/CardInfomation.cs
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/Ver2_CardScene.unity
Labels: fix :hammer:, add :hugs:

#98 [update] カードとスキルシステムを連携させた
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/AddCard.cs
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/CardController.cs
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/CardData/CardInfomation.cs
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/CardSkillController.cs
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/CardSkillController.cs.meta
  KamisamaIntern/Assets/Suebayashi_Folder/CardOption/Ver2_CardScene.unity
  KamisamaIntern/ProjectSettings/TagManager.asset
Labels: try out :face_with_head_bandage:

#99 [add]自然/発展ポイントの集計システムとエンディング分岐システムを作りました。
  KamisamaIntern/Assets/Image/ED_A.png.meta
  KamisamaIntern/Assets/Image/ED_B.png.meta
  KamisamaIntern/Assets/Image/ED_C.png.meta
  KamisamaIntern/Assets/Image/ED_D.png.meta
  KamisamaIntern/Assets/Shinya_Folder/Scenes/MakeCardEffectScene.unity
  KamisamaIntern/Assets/Shinya_Folder/Scripts/EndingBranch.cs
  KamisamaIntern/Assets/Shinya_Folder/Scripts/EndingBranch.cs.meta
  KamisamaIntern/Assets/Shinya_Folder/Scripts/PointCount.cs
  KamisamaIntern/Assets/Shinya_Folder/Scripts/PointCount.cs.meta
  KamisamaIntern/Assets/Suebayashi_Folder/EndingScene.unity
Labels: enhancement 💪, try out :face_with_head_bandage:, add :hugs:

#108 [add] タイトル画面と、ゲームメインシーンでカードの機能追加
  KamisamaIntern/Assets/Scenes/GameScene_Main.unity
  KamisamaIntern/Assets/Shinya_Folder/Resources/Human 1.prefab
  KamisamaIntern/Assets/Shinya_Folder/Scripts/StorySceneController.cs
  KamisamaIntern/Assets/Suebayashi_Folder/TitleScene.unity
  KamisamaIntern/Assets/Tanaka_Folder/Prefab_Tanaka/RandomTreePutManager.prefab
  KamisamaIntern/Assets/Tanaka_Folder/Scripts_Tanaka/Title.meta
  KamisamaIntern/Assets/Tanaka_Folder/Scripts_Tanaka/Title/GoPlayGuideScene.cs
  KamisamaIntern/Assets/Tanaka_Folder/Scripts_Tanaka/Title/GoPlayGuideScene.cs.meta
  KamisamaIntern/Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
  KamisamaIntern/ProjectSettings/EditorBuildSettings.asset
Labels: enhancement 💪

#109 [add] 遊び方画面を作成した
  KamisamaIntern/Assets/Shinya_Folder/Scenes/PlayGuideScene.unity
  KamisamaIntern/Assets/Shinya_Folder/Scenes/PlayGuideScene.unity.meta
  KamisamaIntern/Assets/Shinya_Folder/Scripts/ExplainController.cs
  KamisamaIntern/Assets/Shinya_Folder/Scripts/TileExplainController.cs
  KamisamaIntern/Assets/Suebayashi_Folder/TitleScene.unity
Labels: add :hugs:

#120 [add]ユニットのレイヤー修正と人間のLayerの修正を行いました。
  KamisamaIntern/Assets/Shinya_Folder/Resources/Burnt_Field.prefab
  KamisamaIntern/Assets/Shinya_Folder/Resources/Factory.prefab
  KamisamaIntern/Assets/Shinya_Folder/Resources/Human 1.prefab
  KamisamaIntern/Assets/Shinya_Folder/Resources/WorldTree.prefab
  KamisamaIntern/Assets/Shinya_Folder/Resources/field.prefab
Labels: fix :hammer:

#121 [fix] ストーリーシーンのCanvas部品の位置調整・背景画像の差し替えを行った
  KamisamaIntern/Assets/Image/Story_noTitle.png
  KamisamaIntern/Assets/Image/Story_noTitle.png.meta
  KamisamaIntern/Assets/Shinya_Folder/Scenes/StoryScene.unity
Labels: fix :hammer:

#123 [fix]人間のCollider設定を変更した。
  KamisamaIntern/Assets/GameScene/GameScene_Main.unity
  KamisamaIntern/Assets/GameScene/Resources/Human 1.prefab
  KamisamaIntern/Assets/GameScene/Resources/tree.prefab
  KamisamaIntern/Assets/ImportedAsset/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
  KamisamaIntern/ProjectSettings/BurstAotSettings_StandaloneWindows.json
  KamisamaIntern/ProjectSettings/CommonBurstAotSettings.json
  KamisamaIntern/ProjectSettings/EditorBuildSettings.asset
  KamisamaIntern/ProjectSettings/Physics2DSettings.asset
  KamisamaIntern/ProjectSettings/TagManager.asset
Labels: bug :bug: :adhesive_bandage:
